Updated check_switch_psu to also check psu status.

diff --git a/SOURCES/smorg-nagios-plugins-extra-1/check_switch_psu b/SOURCES/smorg-nagios-plugins-extra-1/check_switch_psu
--- a/SOURCES/smorg-nagios-plugins-extra-1/check_switch_psu
+++ b/SOURCES/smorg-nagios-plugins-extra-1/check_switch_psu
@@ -53,13 +53,33 @@ declare -a entPhysicalContainedIn
 declare -a entPhysicalContainedIn_id
 declare -a entPhysicalClass
 declare -a entPhysicalClass_id
+declare -a cefcFRUPowerOperStatus
+declare -a cefcFRUPowerOperStatus_id
 declare -a show
 declare -a alert
 
 
-entPhysicalDescr_oid=1.3.6.1.2.1.47.1.1.1.1.2
-entPhysicalContainedIn_oid=1.3.6.1.2.1.47.1.1.1.1.4
-entPhysicalClass_oid=1.3.6.1.2.1.47.1.1.1.1.5
+entPhysicalDescr_oid=.1.3.6.1.2.1.47.1.1.1.1.2
+entPhysicalContainedIn_oid=.1.3.6.1.2.1.47.1.1.1.1.4
+entPhysicalClass_oid=.1.3.6.1.2.1.47.1.1.1.1.5
+cefcFRUPowerOperStatus_oid=.1.3.6.1.4.1.9.9.117.1.1.2.1.2
+
+# cefcFRUPowerOperStatus,PowerOperType:
+declare -a PowerOperType=(
+			"dummy"               # <- not used, dummy for index 0
+                        "offEnvOther"
+                        "on"
+                        "offAdmin"
+                        "offDenied"
+                        "offEnvPower"
+                        "offEnvTemp"
+                        "offEnvFan"
+                        "failed"
+                        "onButFanFail"
+                        "offCooling"
+                        "offConnectorRating"
+                        "onButInlinePowerFail"
+                       )
 
 # See CISCO-ENTITY-FRU-CONTROL-MIB
 #declare -a PowerRedundancyType=(
@@ -174,7 +194,7 @@ usage()
     echo
     echo " -h         :  Display this help text."
     echo " -v         :  Display the version of this script."
-    echo " -l         :  List all available ports and their status."
+    echo " -l         :  List hardware."
     echo " -c SECRET  :  Community string."
     echo
     echo "Check that 2 power supplies are working."
@@ -211,6 +231,35 @@ array_search()
 }
 
 # ---------------------------------------------------------------------------
+check_psus_have_good_status()
+# ---------------------------------------------------------------------------
+# The PSUs are present. Check that they have an ok status.
+# $1 - ID of the first PSU
+# $2 - ID of the second PSU
+# Returns 0,1,2 or 3 (OK, WARN, CRITICAL, Unknown).
+# 0 - 2 psu
+# 1 - 1 psu
+# 2 - no psu (not possible)
+# 3 - program error
+{
+    local retval=$OK x=1
+
+    echo -n "Status"
+
+    for i in `seq 0 $((${#cefcFRUPowerOperStatus_id[*]}-1))`
+    do
+        [[ ! ( ${cefcFRUPowerOperStatus_id[i]} -eq $1 || \
+               ${cefcFRUPowerOperStatus_id[i]} -eq $2 ) ]] && continue
+        echo -n " PSU-$x:(${PowerOperType[${cefcFRUPowerOperStatus[i]}]})"
+        : $((++x))
+    done
+
+    echo "."
+
+    return $retval
+}
+
+# ---------------------------------------------------------------------------
 psu_alert_status()
 # ---------------------------------------------------------------------------
 # Outputs status text
@@ -227,12 +276,14 @@ psu_alert_status()
 
     for i in $psus; do
         name="${entPhysicalDescr[i]}"
+        id[x]="${entPhysicalDescr_id[i]}"
         : $((++x))
     done
 
     if [[ $x -eq 2 ]]; then
-        echo "PSUs are working (2 x $name)."
-        retval=$OK
+        echo -n "PSUs are working (2 x $name). "
+        check_psus_have_good_status ${id[0]} ${id[1]}
+        retval=$?
     elif [[ $x -eq 1 ]]; then
         echo "Only one PSU is working."
         retval=$WARN
@@ -298,6 +349,15 @@ fill_arrays()
     get_snmp_tree "entPhysicalClass" "$entPhysicalClass_oid"
 
     tnum=${#entPhysicalClass[*]}
+
+    [[ $tnum -lt 2 ]] && {
+        echo "Unknown: No records. Check the community string. Aborting."
+        exit $UNKN
+    }
+
+    get_snmp_tree "cefcFRUPowerOperStatus" "$cefcFRUPowerOperStatus_oid"
+
+    tnum=${#cefcFRUPowerOperStatus[*]}
 
     [[ $tnum -lt 2 ]] && {
         echo "Unknown: No records. Check the community string. Aborting."
